spring:
  profiles:
    active:
    - dev

---
spring:
  application:
    name: springcloud-config-eureka
  profiles: dev

server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false
    fetch-registry: false

---
spring:
  application:
    name: springcloud-config-eureka
  profiles: test

server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false
    fetch-registry: false