spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001


spring:
  profiles: dev
  application:
    name: springcloud-config-dept-client
  datasource:
    url: jdbc:mysql://120.27.249.14:3306/clouddb01
    username: root
    password: 123456
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  instance:
    instance-id: config-dept-8001
    prefer-ip-address: true
  client:
    service-url: http://eureka7001.com:7001/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
  type-aliases-package: com.mercer.springcloud.entities

info:
  app.name: study-springcloud-micoservices
  company.name: www.mercer.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---
server:
  port: 8001


spring:
  profiles: test
  application:
    name: springcloud-config-dept-client
  datasource:
    url: jdbc:mysql://120.27.249.14:3306/clouddb02
    username: root
    password: 123456
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  instance:
    instance-id: config-dept-8001
    prefer-ip-address: true
  client:
    service-url: http://eureka7001.com:7001/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
  type-aliases-package: com.mercer.springcloud.entities

info:
  app.name: study-springcloud-micoservices
  company.name: www.mercer.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}